### ISSUE TITLE
OpenDungeons 0.5.0's cmake.patch should be dropped

### ISSUE THREAD

**Issue by akien-mga** [ckorn/PlayDeb#25]
Hi @ckorn,

A Mint user reported on #opendungeons that the game launcher can't find the OGRE renderers when installed via PlayDeb. As we've discussed together on IRC, I think you should drop the cmake.patch (though I wonder how it even applies properly on the OD 0.5.0 CMakeLists.txt, as the install instructions changed).

I'm a packager myself so there shouldn't be much to patch anyway in the OpenDungeons buildsystem, I always try to make sure that it will "make install" flawlessly and be distro-friendly.

**Comment by ckorn** [comment]
Fixed by ef9ec48ecc91f83bab1b00a46a6473559dc8e82a .

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
I guess the commit should also be cherry-picked for the vivid branch?

_Edit:_ Nevermind, the patch had already been dropped in vivid.

**Comment by ckorn** [comment]
The patch was already removed in the vivid branch: b503212443ddc589a32a9158d9b146fae1df05ad
Just forgot to also remove it from the trusty branch.
