### ISSUE TITLE
Tales of Maj'Eyal - 404 not found (xenial)

### ISSUE THREAD

**Issue by pizzadude** [ckorn/PlayDeb#44]
E: Failed to fetch http://archive.getdeb.net/ubuntu/pool/games/t/tales-of-majeyal/tales-of-majeyal-data_1.5.0-1~getdeb1_all.deb 404  Not Found

E: Failed to fetch http://archive.getdeb.net/ubuntu/pool/games/t/tales-of-majeyal/tales-of-majeyal_1.5.0-1~getdeb1_amd64.deb 404  Not Found

**Comment by ckorn** [comment]
Just published a new version.

Please run:
sudo apt-get update

**Comment by pizzadude** [comment]
Ok, thanks. I donated to playdeb btw.

**Comment by ckorn** [comment]
Thank you for that. It is very appreciated.

I can set up a link for you on the sponsor page if you like.

**Comment by pizzadude** [comment]
It was a one time donation, but if that's ok, can you link it as "PizzaDude.ca" and the url "http://pizzadude.ca"

**Comment by ckorn** [comment]
Just added your donation as 1€ subscription for four months.
