### ISSUE TITLE
rbdoom3bfg patches

### ISSUE THREAD

**Issue by darealshinji** [ckorn/PlayDeb#5]
I made some patches to rbdoom3bfg. One patch enables the usage of system libraries instead of using static embedded libs. And there are other small fixes made from yet unmerged upstream pull requests.
https://launchpad.net/~djcj/+archive/games/+packages
Note that the Ubuntu 12.04 version can't use the system's glew library, or the build fails. Maybe you can use some of this.

**Comment by ckorn** [comment]
Hum, the SDL version crashes here although the version on PlayDeb is also SDL and does not crash.

Also the non SDL version runs but the resolution is changed. I have two black bars left and right on my screen where I cannot even move my mouse to.

**Comment by darealshinji** [comment]
Interresting. Can you confirm if that comes from one of the patches?

**Comment by ckorn** [comment]
It seems to be the system lib patch. With it applied I had the problem that the non SDL version did not close and I had to kill it (although I did not get the black bars this time).
The SDL version does not start at all. This is the output:
http://sprunge.us/ISiV

**Comment by ckorn** [comment]
Why does the package suggest winetricks btw?

**Comment by darealshinji** [comment]
Winetricks to install Steam for Windows and decrypt the game data, as suggested in the readme.
